/**
 * Realistic mock live streams for StreamView.
 * Designed to demonstrate contextual hashtag discovery, category filtering, and Multi View layouts.
 */
export const MOCK_STREAMS = [
  {
    id: "stream_1",
    channelName: "gta_roleplay",
    title: "NEW RP FOR TIWARI & bcb #yatraroleplay",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 1420,
    thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://files.kick.com/images/user/58617046/profile_image/conversion/7ebdaa84-a06f-42ee-82c5-493c39879093-fullsize.webp",
    isLive: true,
    tags: ["GTA RP", "Roleplay", "Hindi", "Police"],
  },
  {
    id: "stream_2",
    channelName: "sorebowgg",
    title: "Haanji Kaiseeee? #yatraroleplay",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 842,
    thumbnailUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://files.kick.com/images/user/72388055/profile_image/conversion/1cfef68c-d855-49b5-b84b-9f0a33448719-fullsize.webp",
    isLive: true,
    tags: ["GTA RP", "Roleplay", "Hindi"],
  },
  {
    id: "stream_3",
    channelName: "SHREEPlayZ",
    title: "SMG INCOMING? #yatraroleplay",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 531,
    thumbnailUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://files.kick.com/images/user/58429116/profile_image/conversion/a12bd8dd-0cc2-491b-b91d-01f9a5114d15-fullsize.webp",
    isLive: true,
    tags: ["GTA RP", "Police RP", "Hindi"],
  },
  {
    id: "stream_4",
    channelName: "X_Gaming",
    title: "GTA RP #yatraroleplay | Chase Day with Gang",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 1210,
    thumbnailUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=X_Gaming&backgroundColor=b6e3f4,ffd5dc",
    isLive: true,
    tags: ["GTA RP", "Roleplay", "Action"],
  },
  {
    id: "stream_5",
    channelName: "ViperLive",
    title: "Court Case Today! City Lawyer RP #yatraroleplay",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 678,
    thumbnailUrl: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=ViperLive&backgroundColor=c0aede,ffdfbf",
    isLive: true,
    tags: ["GTA RP", "Lawyer", "Hindi"],
  },
  {
    id: "stream_6",
    channelName: "Raka_Plays",
    title: "Night Patrol as Captain | GTA V Police RP",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 920,
    thumbnailUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Raka_Plays&backgroundColor=b6e3f4,c0aede",
    isLive: true,
    tags: ["GTA RP", "Police", "Hindi"],
  },
  {
    id: "stream_7",
    channelName: "WestCoastRP",
    title: "NoPixel 4.0 | Big heist setup with the boys #gta5rp",
    category: "Grand Theft Auto V",
    language: "English",
    viewerCount: 3450,
    thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=WestCoastRP&backgroundColor=d1d4f9,ffd5dc",
    isLive: true,
    tags: ["GTA RP", "NoPixel", "English", "Heist"],
  },
  {
    id: "stream_8",
    channelName: "TacticalGamer",
    title: "Ranked Faceit Level 10 Grind! 20+ Kills #cs2",
    category: "Counter-Strike 2",
    language: "English",
    viewerCount: 1850,
    thumbnailUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=TacticalGamer&backgroundColor=ffdfbf,ffd5dc",
    isLive: true,
    tags: ["FPS", "Competitive", "Esports"],
  },
  {
    id: "stream_9",
    channelName: "RadiantAces",
    title: "Immortal 3 Duo Queue | Jett & Reyna only",
    category: "Valorant",
    language: "English",
    viewerCount: 2100,
    thumbnailUrl: "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=RadiantAces&backgroundColor=b6e3f4,c0aede",
    isLive: true,
    tags: ["FPS", "Valorant", "Ranked"],
  },
  {
    id: "stream_10",
    channelName: "LoungeVibes",
    title: "Late night community chill & gaming news talk",
    category: "Just Chatting",
    language: "English",
    viewerCount: 3200,
    thumbnailUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=LoungeVibes&backgroundColor=d1d4f9,ffdfbf",
    isLive: true,
    tags: ["Chill", "Chatting", "Podcast"],
  },
  {
    id: "stream_11",
    channelName: "ApexPredator",
    title: "Top 50 Predator Ranked lobbies with the squad",
    category: "Apex Legends",
    language: "English",
    viewerCount: 1650,
    thumbnailUrl: "https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=ApexPredator&backgroundColor=b6e3f4,ffd5dc",
    isLive: true,
    tags: ["Apex", "Ranked", "FPS"],
  },
  {
    id: "stream_12",
    channelName: "DesiGamerClub",
    title: "GTA V Stunt Races with Subscribers! Join room",
    category: "Grand Theft Auto V",
    language: "Hindi",
    viewerCount: 1100,
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=640&h=360&fit=crop&q=80",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=DesiGamerClub&backgroundColor=ffd5dc,c0aede",
    isLive: true,
    tags: ["GTA V", "Races", "Hindi"],
  }
];
